-- AlterTable
ALTER TABLE `PracticeTest` MODIFY `category` ENUM('AMERICAN_GOVERNMENT', 'AMERICAN_HISTORY', 'INTEGRATED_CIVICS', 'SYMBOLS_AND_HOLIDAYS') NULL;

-- AlterTable
ALTER TABLE `Question` ADD COLUMN `dynamicOfficialKey` ENUM('PRESIDENT', 'VICE_PRESIDENT', 'SPEAKER_OF_THE_HOUSE', 'CHIEF_JUSTICE') NULL,
    MODIFY `category` ENUM('AMERICAN_GOVERNMENT', 'AMERICAN_HISTORY', 'INTEGRATED_CIVICS', 'SYMBOLS_AND_HOLIDAYS') NOT NULL;

-- CreateTable
CREATE TABLE `DynamicOfficial` (
    `id` VARCHAR(191) NOT NULL,
    `key` ENUM('PRESIDENT', 'VICE_PRESIDENT', 'SPEAKER_OF_THE_HOUSE', 'CHIEF_JUSTICE') NOT NULL,
    `currentValue` VARCHAR(191) NOT NULL,
    `sourceUrl` VARCHAR(191) NULL,
    `lastVerifiedAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `DynamicOfficial_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
